log:
  access: /tmp/access.log
  error: /tmp/error.log
  loglevel: none
  dnslog: false
dns:
  servers:
    - address: 'tcp+local://8.8.8.8:53'
    - address: 'tcp+local://8.8.4.4:53'
    - address: 127.0.0.11
inbounds:
  - port: 443
    protocol: trojan
    settings:
      clients:
        - password: PASSWORD
    streamSettings:
      network: ws
      wsSettings:
        path: WSPATH
      sockopt:
        tcpcongestion: bbr
outbounds:
  - tag: direct
    protocol: freedom
    settings:
      domainStrategy: UseIPv4
    streamSettings:
      sockopt:
        tcpcongestion: bbr
  - tag: dns-out
    protocol: dns
routing:
  domainStrategy: IPIfNonMatch
  domainMatcher: hybrid
  rules:
    - type: field
      outboundTag: dns-out
      network: udp
      port: 53
