log:
  loglevel: none
  dnslog: false
dns:
  servers:
    - address: 'tcp+local://8.8.8.8:53'
    - address: 'tcp+local://8.8.4.4:53'
inbounds:
  - listen: 0.0.0.0
    port: 443
    protocol: trojan
    settings:
      clients:
        - password: PASSWORD
    streamSettings:
      network: ws
      wsSettings:
        path: WSPATH
      sockopt:
        tcpcongestion: bbr
outbounds:
  - tag: direct
    protocol: freedom
    settings:
      domainStrategy: UseIPv4
    streamSettings:
      sockopt:
        tcpcongestion: bbr
  - tag: dns-out
    protocol: dns
routing:
  domainStrategy: AsIs
  domainMatcher: hybrid
  rules:
    - type: field
      outboundTag: dns-out
      network: udp
      port: 53
