log:
  loglevel: none
dns:
  servers:
    - address: 127.0.0.11
      port: 53
  queryStrategy: UseIPv4
inbounds:
  - port: 8080
    protocol: trojan
    settings:
      clients:
        - password: PASSWORD
    streamSettings:
      network: ws
      wsSettings:
        path: WSPATH
      sockopt:
        tcpcongestion: bbr
    sniffing:
      enabled: true
      destOverride:
        - http
        - tls
      routeOnly: true
outbounds:
  - protocol: freedom
    tag: direct
    settings:
      domainStrategy: UseIPv4
    streamSettings:
      sockopt:
        tcpcongestion: bbr
  - tag: dns-out
    protocol: dns
  - protocol: blackhole
    settings:
      response:
        type: http
    tag: block
routing:
  domainStrategy: AsIs
  rules:
    - type: field
      outboundTag: dns-out
      network: udp
      port: 53
    - type: field
      outboundTag: block
      domain:
        - 'geosite:category-ads-all'
        - 'geosite:cn'
    - type: field
      outboundTag: block
      ip:
        - 'geoip:cn'
        - 'geoip:private'
