log:
  access: '/tmp/access.log'
  error: '/tmp/error.log'
  loglevel: warning
  dnslog: true
dns:
  servers:
    - address: 127.0.0.1
      port: 53
inbounds:
  - port: 443
    protocol: trojan
    settings:
      clients:
        - password: PASSWORD
      fallbacks:
        - dest: 3000
    streamSettings:
      network: ws
      wsSettings:
        path: WSPATH
      sockopt:
        tcpcongestion: bbr
    sniffing:
      enabled: true
      destOverride:
        - http
        - tls
outbounds:
  - tag: direct
    protocol: freedom
    settings:
      domainStrategy: UseIPv4
    streamSettings:
      sockopt:
        tcpcongestion: bbr
  - tag: dns-out
    protocol: dns
  - tag: block
    protocol: blackhole
    settings:
      response:
        type: http
routing:
  domainStrategy: IPIfNonMatch
  rules:
    - type: field
      outboundTag: dns-out
      network: udp
      port: 53
    - type: field
      outboundTag: block
      domain:
        - 'geosite:category-ads-all'
        - 'geosite:cn'
    - type: field
      outboundTag: block
      ip:
        - 'geoip:cn'
        - 'geoip:private'
