log:
  loglevel: info
  dnslog: true
dns:
  servers:
    - address: 'tcp+local://1.1.1.1:53'
    - address: 'tcp+local://1.0.0.1:53'
inbounds:
  - listen: 0.0.0.0
    port: 443
    protocol: trojan
    settings:
      clients:
        - password: PASSWORD
    streamSettings:
      network: ws
      wsSettings:
        path: WSPATH
outbounds:
  - tag: direct
    protocol: freedom
    settings:
      domainStrategy: UseIPv4
  - tag: dns-out
    protocol: dns
routing:
  domainStrategy: AsIs
  rules:
    - type: field
      outboundTag: dns-out
      network: udp
      port: 53
